"""add username and avatar 

Revision ID: de5268e44cd2
Revises: 5674bb38503f
Create Date: 2025-09-27 09:54:40.144724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de5268e44cd2'
down_revision: Union[str, Sequence[str], None] = '5674bb38503f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=320), server_default='', nullable=False))
    op.add_column('user', sa.Column('avatar', sa.String(length=320), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
